title: Making Trails
description: This is the travel blog of Lauren Nishizaki.
baseurl: /making-trails

markdown: kramdown

# jekyll-paginate-v2 settings
pagination:
  enabled: true
  per_page: 10
  permalink: "/page:num/"
  title: ":title"
  sort_reverse: true
autopages:
  enabled: false

permalink: /:year/:title/
