name: Making Trails
description: the travel blog of Lauren Nishizaki
copyright: All rights reserved.

author:
  name: Lauren Nishizaki
  github: https://github.com/lemonnish

baseurl: /making-trails

markdown: kramdown

# jekyll-paginate-v2 settings
pagination:
  enabled: true
  per_page: 10
  permalink: "/page:num/"
  title: ":title"
  sort_reverse: true
autopages:
  enabled: false

permalink: /:year/:title/
